//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlowLearnerEntities : DbContext
    {
        public SlowLearnerEntities()
            : base("name=SlowLearnerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<AppointmentPractic> AppointmentPractic { get; set; }
        public virtual DbSet<AppointmentTest> AppointmentTest { get; set; }
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientTestCollectionFeedback> PatientTestCollectionFeedback { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonIdentification> PersonIdentification { get; set; }
        public virtual DbSet<PersonIdentificationFeedback> PersonIdentificationFeedback { get; set; }
        public virtual DbSet<PersonPicture> PersonPicture { get; set; }
        public virtual DbSet<PersonPracticCollection> PersonPracticCollection { get; set; }
        public virtual DbSet<PersonPractice> PersonPractice { get; set; }
        public virtual DbSet<PersonTest> PersonTest { get; set; }
        public virtual DbSet<PersonTestCollection> PersonTestCollection { get; set; }
        public virtual DbSet<Practice> Practice { get; set; }
        public virtual DbSet<PracticeCollection> PracticeCollection { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestCollection> TestCollection { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPatient> UserPatient { get; set; }
    }
}
