//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTestCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonTestCollection()
        {
            this.PersonIdentificationFeedback = new HashSet<PersonIdentificationFeedback>();
        }
    
        public int id { get; set; }
        public Nullable<int> personId { get; set; }
        public Nullable<int> personTestId { get; set; }
        public Nullable<int> op1 { get; set; }
        public Nullable<int> op2 { get; set; }
        public Nullable<int> op3 { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Person Person2 { get; set; }
        public virtual Person Person3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonIdentificationFeedback> PersonIdentificationFeedback { get; set; }
        public virtual PersonTest PersonTest { get; set; }
    }
}
