//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPracticCollection
    {
        public int id { get; set; }
        public Nullable<int> personId { get; set; }
        public Nullable<int> personPractice { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonPractice PersonPractice1 { get; set; }
    }
}
