//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonIdentification
    {
        public int id { get; set; }
        public Nullable<int> persontestid { get; set; }
        public Nullable<int> patientId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual PersonTest PersonTest { get; set; }
    }
}
