//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LernSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeCollection
    {
        public int id { get; set; }
        public int collectId { get; set; }
        public int pracId { get; set; }
    
        public virtual Practice Practice { get; set; }
    }
}
